### ISSUE TITLE
iPad / iOs support ?

### ISSUE THREAD

**Issue by fyyyyy** [fredemmott/OpenKneeboard#104]
I believe the most common tablet people have is the iPad & iPhone, and 3rd party stylus pens for iPads of a any generation are inexpensive.
Are there technical reasons for not supporting iOs devices ?

**Comment by fredemmott** [comment]
This might eventually be supported via safari and #8 - as for native support, yes, there’s technical reasons - it would need to be an entirely separate code base:

* iOS devices are separate computers, unlike Wacom and huion tablets which are input devices for windows (and mac) computers.
* iOS devices do not support the Wintab API
* for display, iOS devices to not support direct2D/direct3D
