### ISSUE TITLE
Relabel 'gaze target' settings to clarify they're not just for zoom any more

### ISSUE THREAD

**Issue by BG168** [fredemmott/OpenKneeboard#106]
Currently to engage the "opacity when looking at kneeboard" feature, I have to nearly center the kneeboard in my VR field of view.  It would be nice to be able to adjust the sensitivity so that this feature closer to one's peripheral vision.

**Comment by fredemmott** [comment]
@BG168 are you wanting that for 'looking at kneeboard' sensitivity as well as position? I understood that for #105

**Comment by BG168** [comment]
No, disregard, I misread your reply and thought it was for the other one.  This is all good, thanks!
