### ISSUE TITLE
How does one install this?

### ISSUE THREAD

**Issue by Lange666** [fredemmott/OpenKneeboard#23]
On 90% of the software offered here on Github i always stumble over the same problem:
Either which file to download or on how to install it.
How much i appreciate the effort of the developers... this one is no different... :-(
Or do i miss something?

**Comment by fredemmott** [comment]
It can be downloaded from the automatic builds under “actions” -> “artifacts” - however it is currently primarily intended for developers who are comfortable building it themselves. Easy installation by non developers will not be a goal until the project is more mature

**Comment by fredemmott** [comment]
>On 90% of the software offered here on Github

If the developers consider something ready for general use, you usually want the 'Releases' link on the right hand side. Within the files attached to a release (labelled 'assets'), you usually want a .exe or .zip which isn't labelled 'source code' or 'debug'.
