### ISSUE TITLE
Request: Allow OpenKneeboard to insert itself as a page in built-in DCS kneeboard.

### ISSUE THREAD

**Issue by TaylorMonkey** [fredemmott/OpenKneeboard#34]
This is real cool. Now I have to ask... is it possible for OpenKneeboard to insert itself as pages into the actual DCS kneeboard?

Somehow VAICOM Pro is able to do this. If OpenKneeboard could also do this with its graphics tablet support, it would be the kneeboard to rule all kneeboards.

Any chance of developing that ability?

**Comment by fredemmott** [comment]
Not really, sorry; inserting text or graphics a few times a second is relatively straightforward, but pen strokes need a *much* faster draw rate to be usable.

Something like the radio log/message history is doable by appending the text or swapping out an image, but swapping out an image at the rate needed for usable pen strokes needs *a lot* of CPU, and the RAM < - >  GPU copies destroys frame rate.

When I last posted about OpenKneeboard, it basically worked like this - but adding graphics support basically required rewriting the graphics handling to eliminate RAM < - > GPU copies for the pen strokes in openkneeboard to feel usable. It cut GPU usage by ~ 15x and CPU by ~ 100x when rendering pen strokes at 30fps. This wasn’t an issue previously as without pen strokes, openkneeboard only needed to update 5 times a second tops if you are super agro with the next page binding - it still normally sits at zero FPS if you’re not actively doing anything with it

What would be possible is faking it, without adding pages: keep track of when the kneeboard is visible, what page is displaying, where on the screen it is, and drawing on top of it. I don’t plan to add that as the amount of a shareable code would be pretty minimal - it would be much better done as a different app
