### ISSUE TITLE
Openkneeboard process still running after closing

### ISSUE THREAD

**Issue by franukis** [fredemmott/OpenKneeboard#43]
Closing the app using the "X" on the title bar, it still keeps running
Attached Windbg to process after attempting to close it. dump below:

**Comment by franukis** [comment]
Sorry, cannot attach the file. Will try again later

**Comment by fredemmott** [comment]
If email's better, openkneeboard-issue-43@fred.fredemmott.com

**Comment by fredemmott** [comment]
Is SteamVR still running?

It looks like the SteamVR thread in openkneeboard was asked to shutdown *by SteamVR* before you closed OpenKneeboard, but seems to be blocked forever on waiting for something from the HP driver. It's also still running, and would be the first thread to be shut down.

**Comment by fredemmott** [comment]
To (sometimes) reproduce this:

1. start steamvr with a headset connected
2. launch a RelWithDebInfo version of OpenKneeboard. Does not reproduce with Debug version (yay)
3. exit openkneeboard
4. See it is handing in `VR_Shutdown`

**Comment by fredemmott** [comment]
I can't reproduce this with [OpenKneeboard-RelWithDebInfo.msix](https://github.com/fredemmott/OpenKneeboard/suites/5746675514/artifacts/190698690) from https://github.com/fredemmott/OpenKneeboard/actions/runs/2019660883 - I think this resolves it.

**Comment by franukis** [comment]
> - I think this resolves it. Please let me know.

Indeed it does, just tested :)

**Comment by franukis** [comment]
BTW, great job, this build solves both this issue and #42 

Thank you very much for your effort :)
