### ISSUE TITLE
Add stroke width

### ISSUE THREAD

**Issue by franukis** [fredemmott/OpenKneeboard#44]
It would be nice to have some options to select:

- Stroke color
- Default stroke width (current "one size fits all" might be not appropriate depending on the size of the docs)
- Stroke transparency (to enable highlight marker style)

On a first implementation, this could be just set from the settings menu, with no option of "real time" changing.
An advanced option would be to offer a way to select different pre-defined strokes while in game, through a selector, or through bindings.

**Comment by franukis** [comment]
Working with a Wacom Intuos S here...

Yeah, I was thinking on some additional consistency. But you're right, decreasing sensitivity (moving towards "firm" setting) makes it more manageable, as the default "middle of the field" sensitivity was too much, and making the strokes too wide.

Great to know the plan about UI, no rush :)

**Comment by fredemmott** [comment]
Leaving this just for stroke width, with color/transparency at #66 - still likely to end up with both, just tracking them separately

**Comment by bbirchnz** [comment]
Stroke width options added in #58
