### ISSUE TITLE
Crash at start application with 0.2.3

### ISSUE THREAD

**Issue by DArt503** [fredemmott/OpenKneeboard#47]
It crash every time on launch with 0.2.3, works correctly with previous version. I clean app data from Windows menu, reinstall same thing.
I join the crash dump.
[OpenKneeboardApp.exe.37428.dmp.zip](https://github.com/fredemmott/OpenKneeboard/files/8334886/OpenKneeboardApp.exe.37428.dmp.zip)

Thx for that project !

**Comment by fredemmott** [comment]
> with previous version

Is that 0.2.2, or 0.1.something?

**Comment by DArt503** [comment]
Was 0.1.x (old UI)

**Comment by fredemmott** [comment]
Huh, that looks like it's crashing before my code, but I have the same versions of the libraries :(

Could you see if https://www.microsoft.com/store/productId/9P3JFPWWDZRC opens for you or if it has the same problem?

If you're comfortable with debuggers, it would be really useful to know what's in the stowed exceptions here - the information isn't in the dump:

![image](https://user-images.githubusercontent.com/360927/159805907-4ee923f9-276b-45ad-9f5b-f1916f6630cc.png)

One thing to try:

- uninstall openkneeboard (and winui 3 controls gallery if you install it)
- open powershell
- run `Get-AppxPackage -name "*WindowsAppRuntime*" | Remove-AppxPackage`
- install openkneeboard again

This sounds scary, but:
- the windows app runtime is a *very* new thing (december 2021) and hardly anything depends on it yet
- Remove-AppxPackage will refuse to remove any packages that something else is declared as depending on

**Comment by DArt503** [comment]
no problem, I am the developer of LotAtc so I am not scary about crashes, debugger, powershell or dumps :D

here the results:

- Winui 3 controls gallery works correctly, no problem here
- Uninstall procedure + reinstall gives me same crash at start.

I will try to get the code and compile myself in order to have a solid callstack on debugger!

**Comment by fredemmott** [comment]
> I will try to get the code and compile myself in order to have a solid callstack on debugger!

there's also a debug build and symbols at https://github.com/fredemmott/OpenKneeboard/actions/runs/2022974226 - I removed them from the release page to simplify things for non-developers :)

it does need the windows app SDK debug libraries, which are only available as part of the windows app SDK package though

**Comment by DArt503** [comment]
Test_viewer.exe is working, window opens correctly.

**Comment by fredemmott** [comment]
It's `OpenKneeboardApp.exe` you want to run in the debugger - `OpenKneeboard-Launch-WindowsApp.exe` [is essentially a shortcut](https://github.com/fredemmott/OpenKneeboard/blob/master/src/utilities/launch-msix.cpp) for people that want to launch OpenKneeboard from something else that requires an exe and doesn't support appx/msix/windows store apps

**Comment by DArt503** [comment]
> It's `OpenKneeboardApp.exe` you want to run in the debugger - `OpenKneeboard-Launch-WindowsApp.exe` [is essentially a shortcut](https://github.com/fredemmott/OpenKneeboard/blob/master/src/utilities/launch-msix.cpp) for people that want to launch OpenKneeboard from something else that requires an exe and doesn't support appx/msix/windows store apps

copy, it seems to not been build by default... any special values for CMake I could forgot ? I have just opened the folder in Visual Studio and launch the build.

**Comment by fredemmott** [comment]
in visual studio *code* with cmake extensions, the default 'all' target will build it

otherwise, in the build directory (with a CMakeCache.txt): `cmake --build . --config Debug --parallel` will build everything - it'll then be in something like (sorry, can't check right now) BUILD_DIR/src/app/app-winui-3/msbuild-out-Debug/OpenKneeboardApp.exe

**Comment by fredemmott** [comment]
https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/debugging_crashes.md might be useful, especially https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/debugging_crashes.md#how-to-get-a-good-callstack-for-crashes , which goes into stowed exceptions related to the xaml handling, which matches the original trace/dump

**Comment by DArt503** [comment]
Sorry for late response, I have at current master version of today.
I got same crash at start with last version
I try to build from source but I got that:
![image](https://user-images.githubusercontent.com/32910847/162216575-ca7ef093-87ba-46b2-9765-d64e1a4a6dd6.png)

I think that the problem is certainly due to my dev env but I have not found the reason yet :)

**Comment by DArt503** [comment]
My bad, I installed the .NET tools, it fixes the build. :)

**Comment by DArt503** [comment]
Here is the debug for the openXR alpha version (same behavior than std version):
![image](https://user-images.githubusercontent.com/32910847/162238972-4b42e46e-9242-4108-960c-faa2a140dbd1.png)

**Comment by fredemmott** [comment]
Those constants are defined by the version of the Windows App SDK (which isn't part of the windows SDK) you have installed; I don't understand how it can mismatch for you, though you can download all the runtimes at https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads

**Comment by fredemmott** [comment]
`MddBootstrapInitialize` problems do currently lead to a silent exit (Microsoft are planning to provide alternatives in windows app sdk 1.1), though it's not the same issue as when running from the MSIX, as `isPackaged` is true in those runs

I've hit something similar to the original microsoft ui xaml stowed exception one: this is a pain to debug. It essentially means something, somewhere in the App.xaml.cpp initialization (Which includes the MainWindow.xaml.cpp initialization) threw an exception - but the internals of the xaml library hide the original exception :(

**Comment by DArt503** [comment]
Here is the stack for last release 0.3.0 with your debug symbols. I cannot compile it because it needs visual 20 and I have only visual 19 on my computer. As it is my main dev machine, I prefer not install too much thing on it.

![image](https://user-images.githubusercontent.com/32910847/164967005-8867c2a3-c9c1-4971-b0e9-f5b50b0103cc.png)

It seems to be related to some json settings, so is there some file I can remove ? I try the reset data button from Windows with no success. 
`  if (!mSettings.NonVR.is_null()) {
    mVRConfig = mSettings.VR;
  }`

**Comment by fredemmott** [comment]
![image](https://user-images.githubusercontent.com/360927/164983899-8a1698b4-540f-4715-8f74-9de7d1571786.png)

Could you share the dump, or the source lines for these frames?

> It seems to be related to some json settings, so is there some file I can remove ?

Yep - `Saved Games\OpenKneeboard\Settings.json` - it would also be useful if you can share that

> I try the reset data button from Windows with no success.

Sadly, yes - the places that affects can potentially be automatically deleted when upgrading between versions. It's really intended for caches etc

**Comment by DArt503** [comment]
[_Settings.zip](https://github.com/fredemmott/OpenKneeboard/files/8550123/_Settings.zip)

That's it !!!! It is working now ! Here the faulty settings thx for your support !

**Comment by fredemmott** [comment]
Thanks! https://github.com/fredemmott/OpenKneeboard/commit/1d61a55c26159341df0281e7fd8548c66f0abe65 will have stopped these invalid settings from being saved in the future

**Comment by fredemmott** [comment]
Thanks to v1.1 of the Windows App SDK release last week, as of cd745062b7b4bb38f123ef1d6a9eeafebb59f789 there is no dependency on external framework packages at runtime - everything necessary is in the build/install dir.

**Comment by fredemmott** [comment]
Thanks to v1.1 of the Windows App SDK release last week, as of https://github.com/fredemmott/OpenKneeboard/commit/cd745062b7b4bb38f123ef1d6a9eeafebb59f789 there is no dependency on external framework packages at runtime - everything necessary is in the build/install dir.
