### ISSUE TITLE
Recognize Cougar MFDs as input

### ISSUE THREAD

**Issue by Tisor** [fredemmott/OpenKneeboard#48]
For flying on VR with a home cockpit, is useful to have the cougar MFD buttons available to switch pages and so on.

**Comment by fredemmott** [comment]
Sorry; this originally would accept 'any game controller', but when I added keyboard support, directinput doesn't support 'keyboard and any gamecontroller', or even 'everything, then I'll allow it if it's a keyboard or game controller'

That fix (you can probably download OpenKneeboard-RelWithDebInfo.msix from https://github.com/fredemmott/OpenKneeboard/actions/runs/2031374163 in 10-20 minutes) switches from asking DirectX "what do you think this device is?" to looking at the standard USB device descriptions, in a way that matches the MFDs: according to directinput they're a 'specialist device', USB standard description is 'gamepad'.
