### ISSUE TITLE
Restore previous size of the app when opening

### ISSUE THREAD

**Issue by 000Ready000** [fredemmott/OpenKneeboard#51]
Hi when I open the app the default size is very large and wide on my desktop. I use an ultrawide screen and the app spreads across the whole screen. For example opening the app minimized and remembering last size/location would be very nice.

Cheers, Ready

**Comment by fredemmott** [comment]
Not yet supported by the winui framework: https://github.com/microsoft/microsoft-ui-xaml/issues/2680

However, it probably can be done 'the old fashioned way' with classic win32 APIs like SetWindowPos
