### ISSUE TITLE
Invalid page size and restart/reload

### ISSUE THREAD

**Issue by 000Ready000** [fredemmott/OpenKneeboard#52]
Hi I was adding some new slides to an active kneeboard folder when the app was open. By browsing through the pages I received a 'invalid document size' or 'invalid page size' or something like that. I had to restart the app. Closing it by pressing the X on the top right did not work. I had to kill the process in process explorer and restart.

Maybe a refresh/reload/restart function would be handy?

**Comment by fredemmott** [comment]
Reload: in theory this is built but there's no way to trigger it for the folder tabs - it's there under the hood for the 'smart' tabs when changing mission/aircraft. I'll add a button

Any chance you have example files that cause this?

> Closing it by pressing the X on the top right did not work. I had to kill the process in process explorer and restart.

What version are you running? This should be fixed (well, worked around by going back to a classic windows title bar) in v0.2.2 and above

**Comment by fredemmott** [comment]
Closing:

* restart/reload should no longer be needed in the next version: tabs will automatically load when the files in the folders they point at are added/removed/modified
* need example files for the invalid page size error
