### ISSUE TITLE
'strike target list' from hoggit garbled in radio log tab

### ISSUE THREAD

**Issue by Tony3386** [fredemmott/OpenKneeboard#56]
when radio messages are more than 1 line (in that case 2 lines) radio log tab cant report correctly messages. 
![Screenshot (15)](https://user-images.githubusercontent.com/103175581/162255090-baeb895c-f265-4334-b4fd-f6739db43017.png)
this time i was MP (hoggit)

**Comment by fredemmott** [comment]
This isn't a general problem with multi-line messages; there's something about how those messages are formatted that is causing problems

![image](https://user-images.githubusercontent.com/360927/162352912-a9e17916-bff8-4cd9-aaed-c5b7deb226ab.png)

**Comment by fredemmott** [comment]
![image](https://user-images.githubusercontent.com/360927/162353941-ecf192a6-f9e0-43e3-9d60-2f3ea0603453.png)

ah there we go, it's when the message contains tab characters. OpenKneeboard currently that all characters are the same width when using a fixed-width font, btu that's not the case for tabstops
