### ISSUE TITLE
Gaze target settings >x1.0 don't seem to work in OpenXR

### ISSUE THREAD

**Issue by AndLindemann** [fredemmott/OpenKneeboard#60]
I played around with the gaze target settings a bit, as on x1.0 I have to look down a bit too much to be comfortable to get the kneeboard to zoom in, but it seems in OpenXR anything bigger than x1.0 doesn't really have any effect for me.

Compared it to SteamVR Home and there I can see a noticable difference when increasing the gaze target, but in OpenXR for me that doesn't seem to be the case, so probably an OpenXR related issue.

**Comment by fredemmott** [comment]
Thanks, fixed by f003200b57c2058443a640c18bd9e70ebf114d86
