### ISSUE TITLE
Add wacom (wintab) support

### ISSUE THREAD

**Issue by fredemmott** [fredemmott/OpenKneeboard#7]
- [x] in-process cursor
- [x] add `DrawableTab` subclass of `Tab`, move all existing tabs to it
- [x] intercept in external apps (injected DLL + `WindowProc` hook + IPC)
- [ ] add drawing options (color, erase etc) to `DrawableTab`
- [ ] tab/page navigation buttons

`DrawableTab`: this should be handled in the tab class rather than another layer to allow tabs to have special behavior, e.g. have buttons that you tap with the stylus, instead of drawing.

**Comment by rollnthndr** [comment]
Any chance of Huion tablet support as well?

**Comment by fredemmott** [comment]
In theory, wintab doesn't support making things wacom-specific; whether it actually works in practice this depends on the quality of the hardware manufacturer's driver. Once Wacom tablets work, Huion tablets..

- ... might 'just work'
- ... might need VRK's special driver (I don't know what that actually does - if it's an alternative wintab driver for Huion, it should do the trick)
- ... might need someone with a Huion tablet to send a pull request implementing dedicated support

**Comment by rollnthndr** [comment]
Ok, I guess we see what happens!

**Comment by fredemmott** [comment]
Looking at Huion's configuration application screenshots, I suspect the tablet will work, but the buttons on the tablet won't

If that's the case, #19 and setting them to unusual key combinations in the Huion software is probably the easiest way to go, with the least interference with other applications

**Comment by fredemmott** [comment]
![image](https://user-images.githubusercontent.com/360927/152084908-cd8bd894-dd23-4ecc-92b8-76e09941f7c5.png)

That's a start :)

**Comment by fredemmott** [comment]
Basic but usable, only tested on wacom, and need these settings:

![image](https://user-images.githubusercontent.com/360927/152274970-21630b1a-1ed6-4941-a325-3f881b716d3e.png)

Tip button ignored, any other button turns it into an eraser.

**Comment by fredemmott** [comment]
Calling this done; will open follow-up issues for enhancements.

**Comment by fredemmott** [comment]
Basics (drawing, pressure sensitivity) work with a Huion H640P, however, Huion only treat the pen tip as an actual button; everything else needs to be done through their software.

This means there will be no direct support for:
- binding a Huion pen button to 'erase'
- binding the buttons on the tablet itself

Supporting more functionality on Huion is probably best done by:
- using Huion's software to bind the buttons to keypresses
- extending the keyboard support in OpenKneeboard (#19)
