### ISSUE TITLE
OpenKneeboard does not appear in the OBS recording

### ISSUE THREAD

**Issue by 000Ready000** [fredemmott/OpenKneeboard#71]
Hi I am using the OBS plugin that comes with the OCXR_WMR_ACC, which records a mirror. In the recording the OpenKneeboard does not appear. How could this be fixed?

**Comment by fredemmott** [comment]
Sorry, I think you need to report this at https://gitlab.com/Jabbah/open-composite-acc/-/issues?sort=created_date&state=opened

It seems likely that the OBS plugin is hooking into OpenXR too early, before other API layers (like OpenKneeboard); it feels likely that a capture plugin should generally try to be the last in the list.

**Comment by fredemmott** [comment]
Summarizing some discord conversations: this isn't really a bug in either - the OBS plugin was originally created as a developer tool, and is designed to show exactly what *the game* sends to openvr/opencomposite. It is not expected to pick up changes made by OpenXR API layers, such as OpenKneeboard.

The best way for is probably to use Oculus/WMR/SteamVR mirror as the recording source, as these show what the Oculus/WMR/SteamVR compositor has produced; alternatives would likely require reimplementing a custom compositor, which would be a lot of work, and likely lead to performance problems as it would be duplicating work the vendor runtimes already have to do.
