### ISSUE TITLE
CTD on selecting DCS Terrain Kneeboard

### ISSUE THREAD

**Issue by piebaker** [fredemmott/OpenKneeboard#77]
As title says. haven't even fired it up in DCS yet, just doing setup. Is the theatre tab the same, could that be it?

- Version 3.0.400-349ff9.
- Custom DCS install location
- Saved games location default
- Installed with MSIX

No other changes from defaults aside from below (not even binds)
- Switched off steam VR support
- Enabled openXR renderer for current user
- Rendering API for open beta set to openXR
- Added custom PDF

**Comment by fredemmott** [comment]
Do you have any OpenKneeboard .dmp files in either `%LOCALAPPDATA%\CrashDumps` or `Saved Games\OpenKneeboard` ?

**Comment by fredemmott** [comment]
Is this happening when selecting 'Terrain' from the left hand side, or from 'add tab' ?

**Comment by piebaker** [comment]
The add tab section. The terrain tab is not loaded by default, so I can't select it from the left-hand pane. 
Dmp files can't be loaded by github it seems, so here's a [onedrive link](https://1drv.ms/u/s!AjPgZz9kdHVGgZhzQhUlisCFzv98Ww?e=zMINbI) to them. 2 localdata dumps and 1 savedgames.

**Comment by fredemmott** [comment]
https://github.com/fredemmott/OpenKneeboard/releases/tag/v0.3.1 should fix this :)

**Comment by piebaker** [comment]
Yup, fixed!
