### ISSUE TITLE
Automatically update file tabs when files are modified

### ISSUE THREAD

**Issue by wonkotron** [fredemmott/OpenKneeboard#85]
It may be beneficial for users without drawing tablets to update the contents of a Text File tab type when the underlying file has been modified.  This would allow users to type notes into a text file, save the file, and display the updated file as a kneeboard tab.

**Comment by fredemmott** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.createitemquerywithoptions is probably the best way to do this - the resulting query has a winrt event for modifications

There's also the classic way to do this: https://docs.microsoft.com/en-us/windows/win32/fileio/obtaining-directory-change-notifications
