### ISSUE TITLE
Add the possibility to reset default seated position

### ISSUE THREAD

**Issue by Ked57** [fredemmott/OpenKneeboard#89]
I find myself reajusting these values in VR everytime I start a session 

![image](https://user-images.githubusercontent.com/2174111/167254439-0141aa71-f229-4d51-a12b-47d09c2d15a0.png)

It would be cool if we had a reset keybind/button to reset the default seated position so the options can all stay the same

**Comment by fredemmott** [comment]
There is a recenter binding under input settings :)

**Comment by fredemmott** [comment]
If the height varies and your using a WMR headset:

openxr: try starting WMR first and letting the WMR home environment fully load before starting DCS

steamvr: reset the steamvr/WMR floor level first

**Comment by Ked57** [comment]
oh wow, I bound it but never used it ... sorry then 😄
