### ISSUE TITLE
Conflict between Openkneeboard and OpenXR Tools for WMR

### ISSUE THREAD

**Issue by franukis** [fredemmott/OpenKneeboard#91]
Hi Fred,

I've been investigating the root cause of an issue I was experiencing with OpenXR Tools for WMR, and it looks like it is pointing to Openkneeboard...

I have been seeing the warning in attached image, and I can only get rid of it, if I go into the registry and eliminate the inputs below Khronos/OpenXR/ApiLayers/Implicit (there seemed to be a remaining input there from an Alpha install of openkneeboard OpenXR support).

Now I get the error if Openkneeboard is installed, and I don't get it if it is not... It is a PITA, as it prevents from adjusting OpenXR resolution (the error does not prevent it from running, but will not show the demo scene, and will not show the exact resolution you are adjusting per eye, through OpenXR Tools for WMR)
![unknown](https://user-images.githubusercontent.com/2131144/167563154-4617c678-eccb-4a6d-85e9-1936da619c07.png)

**Comment by franukis** [comment]
According to discussion with @mbucchia in Discord, it could be due to Openkneeboard being installed as a package into Local AppData, instead of inside Windows or Program Files. This, apparently can conflict with OpenXR Tools for WMR and the permissions needed.

Conversation in Discord starts here: [Discord link](https://discord.com/channels/933220354401398785/933225536870830131/973468795744157717)

**Comment by franukis** [comment]
Changing OpenXR support from "All Users" to "Enabled for the current user" seems to have solved the issue :)

**Comment by fredemmott** [comment]
Unfortunately there isn’t enough information here to go on; this works for others, I don’t have a WMR headset, and openkneeboard copies the files outside of the MSIX sandbox to a non virtualized path. The good news is that running for the current user only is actually a better choice anyway.

**Comment by franukis** [comment]
No worries, I'm glad I found a way that works for me. I wanted, nevertheless, to share te info, in case it would ring a bell for you and/or potentially point towards something that needed attention. I don't really remember why my setting was "All users", and happy to hear it is better to have it for current user.

Thx!
