### ISSUE TITLE
UI Not loaded

### ISSUE THREAD

**Issue by piebaker** [fredemmott/OpenKneeboard#95]
Dunno how I managed this one. 
Opening VR kneeboard causes it not to load the config UI, ie, the desktop app. It comes up on the taskbar as a running program, however, no actual UI is displayed. 

Hovering over it results in this: 
![image](https://user-images.githubusercontent.com/73162560/169473463-c520bd95-3ad8-475c-bf18-ecce6cb2391c.png)

Win+Tab has it looking like this: 
![image](https://user-images.githubusercontent.com/73162560/169473582-0872cd84-fe9a-471f-a55e-1129001f643e.png)

Task manager shows it as running:
![image](https://user-images.githubusercontent.com/73162560/169473630-941cc870-9e81-4c6e-bc88-ca2cff091641.png)

But no actual UI to interact with anything is displayed on the desktop. 

The kneeboard loads just fine in DCS, complete with all of my previously setup custom pdfs, keybinds etc. 
I'm guessing it may have something to do with the latest DCS update, as I was having crashing issues with openXR and openkneeboard when it was started before DCS. (Non-conclusive)
I'm happy to reinstall, I just don't really want to lose my custom loaded PDF's and binds. (Is there a way to backup/transfer these?)

**Comment by fredemmott** [comment]
To get things working again:

- make a backup of `Saved Games\OpenKneeboard\Settings.json`
- remove the `App` section of that file

To prevent it from happening again:
- what is the current contents of the `App` section of that file?
- what version of OpenKneeboard are you running?

**Comment by piebaker** [comment]
Awesome, that worked. Contents were:
```
"App": {
    "WindowPositionV2": {
      "Bottom": -31961,
      "Left": -32000,
      "Right": -31840,
      "Top": -32000
    }
```
Version is: 
```
OpenKneeboard
Version 0.3.1.403-0365da

Copyright © 2021-2022 Frederick Emmott.

With thanks to Paul 'Goldwolf' Whittingham for the logo and banner artwork.

Package: FredEmmott.Self.OpenKneeboard_0.3.1.403_x64__qvw5xrmsm8j1t
Built at: 2022-04-24T16:55:59Z
Build type: RelWithDebInfo-Win64
Commited at: 2022-04-24T16:40:44Z
Commit ID: c748ed9dbd5ff87bf7b997188e034949e20365da
```

**Comment by fredemmott** [comment]
> It does also appear that all custom binds, vr positions and pdfs were lost, unfortunately.

if you still have the original file, that can be recovered - need to delete the app section up to and including the “},” just after the bit you copy-pasted :)

——

closing: the top left of -32000 shows this is an issue that’s already fixed for the next release :)

**Comment by fredemmott** [comment]
Thanks to last weeks' release of the 1.1 Windows App SDK, as of cd745062b7b4bb38f123ef1d6a9eeafebb59f789, there are no external dependencies at runtime - everything runs from the build or install directory :)
